# Generated by Django 2.1.5 on 2019-03-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Action')),
                ('face', models.ManyToManyField(to='catalog.Face')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя', max_length=200)),
                ('second_name', models.CharField(help_text='Фамилия', max_length=200)),
                ('third_name', models.CharField(help_text='Отчество', max_length=200)),
                ('number', models.CharField(help_text='Номер телефона в формате: + 7 123-456-7890', max_length=200)),
                ('email', models.CharField(help_text='email адрес', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Representative'),
        ),
    ]
