# Generated by Django 2.1.5 on 2019-03-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190330_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representative',
            options={'verbose_name': 'Представитель', 'verbose_name_plural': 'Представители'},
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_feedback',
            field=models.CharField(default=1, help_text='Чем закончилась встреча', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_info',
            field=models.CharField(default=1, help_text='Bстория взаимоотношений с партнером (когда и по какому каналу (e-mail, телефон, личная встреча и т.п.) мы ранее общались', max_length=50),
            preserve_default=False,
        ),
    ]
