# Generated by Django 2.1.5 on 2019-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190330_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Меропритятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(help_text='Введите названия мероприятия', max_length=200, verbose_name='Меропритятие'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='goal',
            field=models.TextField(help_text='Введите задачу и опишите ее', max_length=1000, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='first_name',
            field=models.CharField(help_text='Имя', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='number',
            field=models.CharField(help_text='Номер телефона в формате: + 7 123-456-7890', max_length=200, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='second_name',
            field=models.CharField(help_text='Фамилия', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='third_name',
            field=models.CharField(help_text='Отчество', max_length=200, verbose_name='Отчество'),
        ),
    ]
