# Generated by Django 2.1.5 on 2019-03-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190330_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_feedback',
            field=models.TextField(help_text='Чем закончилась встреча', max_length=1000),
        ),
    ]
