# Generated by Django 2.1.5 on 2019-03-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190330_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='catalog.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='face',
        ),
        migrations.AddField(
            model_name='partner',
            name='face',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Face'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='partner',
            name='goal',
        ),
        migrations.AddField(
            model_name='partner',
            name='goal',
            field=models.ManyToManyField(to='catalog.Problem'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='number',
            field=models.CharField(help_text='Номер телефона в формате: +7 123-456-7890', max_length=200, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='third_name',
            field=models.CharField(blank=True, help_text='Отчество', max_length=200, verbose_name='Отчество'),
        ),
    ]
