# Generated by Django 2.1.5 on 2019-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190330_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_period',
            field=models.DateTimeField(),
        ),
    ]
