# Generated by Django 2.1.5 on 2019-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190330_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_info',
            field=models.CharField(default=1, help_text='Введите названия мероприятия', max_length=200, verbose_name='Меропритятие'),
            preserve_default=False,
        ),
    ]
