# Generated by Django 2.1.5 on 2019-03-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_action_action_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='action',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='action_goals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='action_partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Partner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='action_info',
            field=models.CharField(help_text='Введите краткое описание мероприятия', max_length=200, verbose_name='Описание'),
        ),
    ]
