# Generated by Django 2.1.5 on 2019-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190330_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название организации'),
            preserve_default=False,
        ),
    ]
