# Generated by Django 2.1.5 on 2019-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_partner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_goals',
        ),
        migrations.AddField(
            model_name='action',
            name='action_goals',
            field=models.ManyToManyField(to='catalog.Problem'),
        ),
    ]
