# Generated by Django 2.1.5 on 2019-03-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190330_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='identification_number',
            field=models.CharField(default=1, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес сайта'),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_summary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_info',
            field=models.CharField(help_text='История взаимоотношений с партнером (когда и по какому каналу (e-mail, телефон, личная встреча и т.п.) мы ранее общались', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название организации'),
        ),
    ]
