# Generated by Django 2.1.5 on 2019-03-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190330_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер юр. лицо', 'verbose_name_plural': 'Партнеры юр. лица'},
        ),
    ]
