# Generated by Django 2.1.5 on 2019-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190330_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='first_name',
            field=models.CharField(blank=True, help_text='Назначить ответственного', max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='problem',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='problem',
            name='third_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
    ]
