# Generated by Django 2.1.5 on 2019-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190330_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='need_time',
            field=models.DateField(default='2019-03-11'),
            preserve_default=False,
        ),
    ]
