# Generated by Django 2.1.5 on 2019-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_problem_need_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tag',
            field=models.CharField(default=1, help_text='Введите тег не более 10 символов', max_length=10, verbose_name='Тэг'),
            preserve_default=False,
        ),
    ]
