# Generated by Django 2.1.5 on 2019-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_partner_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='tag',
            field=models.CharField(blank=True, help_text='Введите тег не более 10 символов', max_length=10, verbose_name='Тэг'),
        ),
    ]
