# Generated by Django 2.1.5 on 2019-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20190330_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(help_text='email адрес', max_length=15),
        ),
    ]
