# Generated by Django 2.1.5 on 2019-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190330_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_url',
            field=models.URLField(blank=True, max_length=100, verbose_name='Адрес сайта'),
        ),
    ]
