# Generated by Django 2.1.5 on 2019-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20190330_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_partner',
        ),
        migrations.AddField(
            model_name='action',
            name='action_partner',
            field=models.ManyToManyField(to='catalog.Partner'),
        ),
    ]
