# Generated by Django 2.1.5 on 2019-03-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20190330_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_summary', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание')),
                ('contact_info', models.CharField(help_text='История взаимоотношений с партнером (когда и по какому каналу (e-mail, телефон, личная встреча и т.п.) мы ранее общались', max_length=50)),
                ('contact_feedback', models.TextField(help_text='Чем закончилась встреча', max_length=1000)),
                ('tag', models.CharField(blank=True, help_text='Введите тег не более 10 символов', max_length=10, verbose_name='Тэг')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Face')),
                ('goal', models.ManyToManyField(to='catalog.Problem')),
                ('representative', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Representative')),
            ],
            options={
                'verbose_name': 'Партнер юр. лицо',
                'verbose_name_plural': 'Партнеры юр. лица',
            },
        ),
    ]
