# Generated by Django 2.1.5 on 2019-03-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_partnerindividual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='representative',
        ),
        migrations.AddField(
            model_name='partner',
            name='representative',
            field=models.ManyToManyField(to='catalog.Representative'),
        ),
        migrations.AlterField(
            model_name='partnerindividual',
            name='representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Representative', verbose_name='ФИО'),
        ),
    ]
