# Generated by Django 2.1.5 on 2019-03-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20190331_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerindividual',
            name='representative',
        ),
        migrations.AddField(
            model_name='partnerindividual',
            name='email',
            field=models.EmailField(default=1, help_text='email адрес', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerindividual',
            name='first_name',
            field=models.CharField(default=1, help_text='Имя', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerindividual',
            name='number',
            field=models.CharField(default=1, help_text='Номер телефона в формате: +7 123-456-7890', max_length=200, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerindividual',
            name='second_name',
            field=models.CharField(default=1, help_text='Фамилия', max_length=200, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerindividual',
            name='third_name',
            field=models.CharField(blank=True, help_text='Отчество', max_length=200, verbose_name='Отчество'),
        ),
    ]
