# Generated by Django 2.1.5 on 2019-03-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20190331_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerindividual',
            name='email',
            field=models.EmailField(help_text='email адрес', max_length=30),
        ),
    ]
