# Generated by Django 2.1.5 on 2019-03-31 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20190331_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Face'),
        ),
        migrations.AlterField(
            model_name='partnerindividual',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Face1'),
        ),
    ]
