# Generated by Django 2.1.5 on 2019-03-31 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20190331_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_goals',
            field=models.ManyToManyField(to='catalog.Problem', verbose_name='Меропритятие'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_partner',
            field=models.ManyToManyField(to='catalog.Partner', verbose_name='Партнеры'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_period',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_time',
            field=models.TimeField(default='00:00:00', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_feedback',
            field=models.TextField(help_text='Чем закончилась встреча', max_length=1000, verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_info',
            field=models.CharField(help_text='История взаимоотношений с партнером (когда и по какому каналу (e-mail, телефон, личная встреча и т.п.) мы ранее общались', max_length=50, verbose_name='Последняя связь'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Face', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='goal',
            field=models.ManyToManyField(to='catalog.Problem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='representative',
            field=models.ManyToManyField(to='catalog.Representative', verbose_name='Представители'),
        ),
        migrations.AlterField(
            model_name='partnerindividual',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Face1', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='need_time',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
