# Generated by Django 2.1.5 on 2019-03-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20190331_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(blank=True, default='Готово', max_length=10, verbose_name='Статус выполнения'),
        ),
    ]
