# Generated by Django 2.1.5 on 2019-03-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20190331_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'get_latest_by': ['action_period'], 'verbose_name': 'Меропритятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
